import type { SiteContent } from "@/lib/content-types";
import { TemplateDefinition } from "./types";

const photo = (name: string) => `/demo-assets/petra-photos/${name.replace(/\.(jpe?g|png)$/i, ".webp")}`;

const demoContent: SiteContent = {
  header: {
    navItems: [
      { label: "O studiu", href: "/about" },
      { label: "Služby", href: "/sluzby" },
      { label: "Konzultace", href: "/konzultace" },
      { label: "E-shop", href: "/shop/" },
      { label: "Průvodce", href: "/kniha" },
      { label: "Návody", href: "/navody" },
      { label: "Akce", href: "/events/" },
      { label: "Kontakt", href: "/jak-podekovat" },
    ],
    logoHref: "/",
    signInHref: "/login",
  },
  hero: {
    title: "Najděte klid pro svůj prostor",
    subtitle: "Demo šablona pro konzultační studio, které propojuje služby, obsah, akce a jednoduchý prodej.",
    ctaText: "O studiu",
    ctaHref: "#o-studiu",
    backgroundImage: photo("hero-1787x880.jpg"),
    mobileImage: photo("hero-mobile-900x1100.jpg"),
    titleColor: "#1f1f1f",
    subtitleColor: "#2d2530",
    panelBackground: "rgba(255, 255, 255, 0.52)",
    primaryButtonBg: "#7c3bb2",
    primaryButtonColor: "#ffffff",
    secondaryButtonText: "Demo e-shop",
    secondaryButtonHref: "/shop",
  },
  newsletter: {
    title: "Získejte ukázkový newsletter",
    body: "Každý měsíc posíláme krátké tipy pro klidnější práci, lepší organizaci prostoru a vědomější rutinu. Formulář je demo, ale stránka působí jako hotový web.",
    buttonText: "Přihlásit se",
    image: photo("newsletter-1428x1102.jpg"),
  },
  about: {
    title: "O Petře",
    body1: "Petra je fiktivní ukázková osobní značka vytvořená pro tuto šablonu. Pomáhá ukázat, jak může vypadat luxusní osobní nebo konzultační web s jemným vizuálním stylem.",
    body2: "Obsah je záměrně univerzální: návštěvník rychle pochopí služby, může projít nabídku, přečíst si podpůrné stránky a zanechat kontakt bez pocitu rozpracovaného prototypu.",
    buttonText: "Více o studiu",
    buttonHref: "/about",
    imageTop: photo("portrait-579x816.jpg"),
    imageBottom: "",
  },
  manifest: {
    sectionTitle: "Vyberte si demo cestu",
    cards: [
      {
        image: photo("product-1080x1080.jpg"),
        badge: photo("badge-new-240x240.jpg"),
        title: "Digitální průvodce",
        text: "Ukázkový produkt pro e-shop: PDF, pracovní list nebo malý digitální kurz pro klienty.",
        btnText: "Zobrazit průvodce",
        btnHref: "/kniha",
      },
      {
        image: photo("membership-card-408x410.jpg"),
        badge: photo("badge-live-240x240.jpg"),
        title: "Živý workshop",
        text: "Demo akce s registrací, popisem programu a jasným CTA pro rezervaci místa.",
        btnText: "Rezervovat místo",
        btnHref: "/events/",
      },
      {
        image: photo("workshop-408x410.jpg"),
        badge: photo("badge-club-240x240.jpg"),
        title: "Členská zóna",
        text: "Ukázka pravidelného programu pro klienty, kteří chtějí opakovaný obsah a podporu.",
        btnText: "Prohlédnout",
        btnHref: "/membership/",
      },
    ],
  },
  pickacard: {
    title: "Interaktivní demo nástroj",
    body: "Tento blok ukazuje, jak může šablona nabídnout jednoduchý interaktivní prvek: výběr karty, krátký dotazník nebo doporučení služby.",
    buttonText: "Spustit demo",
    buttonHref: "/pick-a-card/",
    image: photo("tool-579x816.jpg"),
  },
  oracle: {
    title: "Ukázkový video blok",
    body: "Prostor pro video, webinář nebo krátkou lekci. Placeholder drží původní poměr stran, takže layout zůstává stejný.",
    youtubeUrl: "",
    thumbnailImage: photo("oracle-video-1280x720.jpg"),
  },
  featuredIn: {
    title: "Objevilo se v médiích",
    brands: [
      "Česká televize",
      "Forbes Česko",
      "Seznam Zprávy",
      "Radiožurnál",
      "iDNES.cz",
      "DVTV",
      "Elle Czech",
      "Ženy.cz",
    ],
  },
  footer: {
    newsletterTitle: "Získejte novinky od Petry.",
    copyright: "© 2026 Petra Studio. Všechna práva vyhrazena.",
    helpLabel: "Centrum pomoci",
    contactLabel: "Napište mi",
    footerLinks: [
      { label: "Ochrana osobních údajů", href: "/privacy-policy/" },
      { label: "Obchodní podmínky", href: "/terms-of-use/" },
      { label: "Reklamace a vrácení", href: "/returns/" },
      { label: "Platební podmínky", href: "/payment-plan-terms/" },
      { label: "Podmínky členství", href: "/membership-terms/" },
    ],
    socialLinks: [
      { name: "Facebook", href: "#" },
      { name: "Instagram", href: "#" },
      { name: "YouTube", href: "#" },
      { name: "Pinterest", href: "#" },
      { name: "TikTok", href: "#" },
      { name: "LinkedIn", href: "#" },
    ],
  },
  aboutPage: {
    heroTitle: "O Petře",
    heroSubtitle: "Fiktivní značka pro profesionální demo web osobních služeb.",
    heroImage: photo("about-small-579x305.jpg"),
    bio1: "Petra Studio je ukázkový brand, který demonstruje strukturu osobního konzultačního webu. Má jasnou nabídku, obsahový hub, akce i produkty.",
    bio2: "Stránka je navržená tak, aby šla použít jako výchozí demo pro klienta: není prázdná, nepůsobí genericky a přitom neobsahuje reálné identifikační údaje.",
    bio3: "Všechny obrázky jsou záměrné placeholdery s původními rozměry, takže po výměně assetů zůstane kompozice stabilní.",
    quoteText: "Dobrá demo stránka nemá vysvětlovat, že je demo. Má působit jako fungující web připravený k přepsání.",
    quoteAuthor: "— Petra",
    ctaTitle: "Chcete vidět služby?",
    ctaText: "Projděte si ukázkovou nabídku konzultací, workshopů a digitálních produktů.",
    ctaButtonText: "Zobrazit služby",
    ctaButtonHref: "/sluzby",
    statsItems: [
      { number: "Demo", label: "Fiktivní brand" },
      { number: "1:1", label: "Konzultace" },
      { number: "Online", label: "Rezervace" },
      { number: "CZ", label: "Lokalizace" },
    ],
  },
  pages: [
    {
      id: "about",
      slug: "about",
      title: "O studiu",
      blocks: [
        {
          id: "about-hero",
          type: "hero-section",
          content: "O Petře",
          subtitle: "Ukázková podstránka se strukturou osobního webu a plně fiktivním demo obsahem.",
          heroBgImage: photo("about-page-hero-1787x880.jpg"),
          ctaText: "Zobrazit služby",
          ctaHref: "/sluzby",
        },
        {
          id: "about-two-col",
          type: "two-col",
          imageLeft: true,
          twoColImage: photo("about-profile-579x816.jpg"),
          twoColTitle: "Demo značka bez reálných údajů",
          twoColText: "<p>Petra Studio ukazuje, jak může působit hotový web pro osobní služby, koučink, konzultace nebo jemnější wellness segment.</p><p>Texty jsou konkrétní, ale fiktivní. Díky tomu lze šablonu bezpečně prezentovat bez vazby na původní projekt.</p>",
          twoColBtnText: "Přejít na konzultace",
          twoColBtnHref: "/konzultace",
        },
      ],
    },
    {
      id: "sluzby",
      slug: "sluzby",
      title: "Služby",
      blocks: [
        {
          id: "services-hero",
          type: "banner",
          content: "Ukázková nabídka služeb",
          subtitle: "Tři služby, které dávají návštěvníkovi jasnou představu o struktuře nabídky.",
          ctaText: "Domluvit konzultaci",
          ctaHref: "/konzultace",
          bgImage: photo("services-hero-1787x880.jpg"),
        },
        {
          id: "services-grid",
          type: "cards-grid",
          sectionTitle: "Co může šablona nabídnout",
          cards: [
            {
              image: photo("consultation-600x420.jpg"),
              title: "Úvodní konzultace",
              text: "Krátká placená nebo bezplatná konzultace pro nové klienty.",
              btnText: "Detail služby",
              btnHref: "/konzultace",
            },
            {
              image: photo("workshop-600x420.jpg"),
              title: "Workshop",
              text: "Skupinová akce, webinář nebo živé setkání s rezervací.",
              btnText: "Zobrazit akce",
              btnHref: "/events/",
            },
            {
              image: photo("service-product-600x420.jpg"),
              title: "Digitální produkt",
              text: "PDF průvodce, minikurz nebo členský obsah pro e-shop.",
              btnText: "Otevřít e-shop",
              btnHref: "/shop/",
            },
          ],
        },
      ],
    },
    {
      id: "konzultace",
      slug: "konzultace",
      title: "Konzultace",
      blocks: [
        { id: "consult-title", type: "heading", level: "h1", content: "Rezervace demo konzultace", align: "center" },
        { id: "consult-text", type: "text", content: "<p>Tato stránka simuluje rezervační detail. V ostrém webu by zde byl kalendář, formulář nebo napojení na rezervační systém.</p>", align: "center" },
        { id: "consult-image", type: "image", src: photo("consultation-1200x720.jpg"), alt: "Demo konzultace v ateliéru" },
        { id: "consult-button", type: "button", content: "Pokračovat na kontakt", href: "/jak-podekovat", size: "lg" },
      ],
    },
    {
      id: "shop",
      slug: "shop",
      title: "Demo e-shop",
      blocks: [
        { id: "shop-hero", type: "heading", level: "h1", content: "Demo e-shop", align: "center" },
        {
          id: "shop-grid",
          type: "cards-grid",
          sectionTitle: "Ukázkové produkty",
          cards: [
            { image: photo("shop-guide-1080x1080.jpg"), title: "Digitální průvodce", text: "PDF produkt pro klienty.", btnText: "Zobrazit", btnHref: "/kniha" },
            { image: photo("shop-worksheet-1080x1080.jpg"), title: "Pracovní list", text: "Ukázka malého digitálního produktu.", btnText: "Zobrazit", btnHref: "/navody" },
            { image: photo("shop-bundle-1080x1080.jpg"), title: "Balíček", text: "Kombinace obsahu a konzultace.", btnText: "Zobrazit", btnHref: "/membership/" },
          ],
        },
      ],
    },
    {
      id: "kniha",
      slug: "kniha",
      title: "Průvodce",
      blocks: [
        { id: "guide-two-col", type: "two-col", imageLeft: false, twoColImage: photo("guide-cover-1080x1080.jpg"), twoColTitle: "Ukázkový digitální průvodce", twoColText: "<p>Produktová stránka pro knihu, PDF nebo minikurz. Drží původní vizuální rytmus, ale obsah je plně demo.</p>", twoColBtnText: "Otevřít e-shop", twoColBtnHref: "/shop/" },
      ],
    },
    {
      id: "navody",
      slug: "navody",
      title: "Návody",
      blocks: [
        { id: "tips-title", type: "heading", level: "h1", content: "Demo návody", align: "center" },
        { id: "tips-text", type: "text", content: "<p>Obsahový hub pro články, návody a edukaci. V demu ukazuje strukturu, ne reálný redakční obsah.</p>", align: "center" },
      ],
    },
    {
      id: "events",
      slug: "events",
      title: "Akce",
      blocks: [
        { id: "events-banner", type: "banner", content: "Demo akce a workshopy", subtitle: "Stránka pro webináře, živá setkání nebo komunitní program.", ctaText: "Rezervovat místo", ctaHref: "/konzultace", bgImage: photo("events-banner-1200x720.jpg") },
      ],
    },
    {
      id: "jak-podekovat",
      slug: "jak-podekovat",
      title: "Kontakt",
      blocks: [
        { id: "contact-title", type: "heading", level: "h1", content: "Kontaktujte Petru", align: "center" },
        { id: "contact-text", type: "text", content: "<p>Tady může být kontaktní formulář, platební informace, často kladené dotazy nebo jednoduché instrukce pro klienty.</p>", align: "center" },
        { id: "contact-newsletter", type: "newsletter", content: "Zůstaňte v kontaktu", body: "Demo formulář pro sběr kontaktů." },
      ],
    },
    {
      id: "help",
      slug: "help",
      title: "Centrum pomoci",
      blocks: [
        { id: "help-title", type: "heading", level: "h1", content: "Centrum pomoci", align: "center" },
        { id: "help-text", type: "text", content: "<p>Ukázková podpůrná stránka pro FAQ, návody k nákupu a kontakt na podporu.</p>", align: "center" },
      ],
    },
    {
      id: "privacy-policy",
      slug: "privacy-policy",
      title: "Ochrana osobních údajů",
      blocks: [{ id: "privacy-text", type: "text", content: "<h1>Ochrana osobních údajů</h1><p>Demo právní stránka. V ostrém provozu ji nahraďte skutečným právním textem.</p>" }],
    },
    {
      id: "terms-of-use",
      slug: "terms-of-use",
      title: "Obchodní podmínky",
      blocks: [{ id: "terms-text", type: "text", content: "<h1>Obchodní podmínky</h1><p>Demo podmínky pro prezentaci struktury webu.</p>" }],
    },
    {
      id: "returns",
      slug: "returns",
      title: "Reklamace a vrácení",
      blocks: [{ id: "returns-text", type: "text", content: "<h1>Reklamace a vrácení</h1><p>Ukázková servisní stránka pro e-shop.</p>" }],
    },
    {
      id: "payment-plan-terms",
      slug: "payment-plan-terms",
      title: "Platební podmínky",
      blocks: [{ id: "payment-text", type: "text", content: "<h1>Platební podmínky</h1><p>Demo text pro platební pravidla.</p>" }],
    },
    {
      id: "membership-terms",
      slug: "membership-terms",
      title: "Podmínky členství",
      blocks: [{ id: "membership-text", type: "text", content: "<h1>Podmínky členství</h1><p>Demo stránka pro členský program.</p>" }],
    },
    {
      id: "membership",
      slug: "membership",
      title: "Členská zóna",
      blocks: [{ id: "membership-banner", type: "banner", content: "Členská zóna", subtitle: "Ukázka opakovaného programu nebo předplatného.", ctaText: "Vyzkoušet konzultaci", ctaHref: "/konzultace", bgImage: photo("membership-banner-1200x720.jpg") }],
    },
    {
      id: "pick-a-card",
      slug: "pick-a-card",
      title: "Interaktivní nástroj",
      blocks: [{ id: "tool-image", type: "image", src: photo("tool-page-579x816.jpg"), alt: "Interaktivní demo nástroj" }],
    },
    {
      id: "art-of-manifesting",
      slug: "art-of-manifesting",
      title: "Digitální průvodce",
      blocks: [{ id: "product-image", type: "image", src: photo("product-page-1080x1080.jpg"), alt: "Demo produkt" }],
    },
    {
      id: "oracle-secrets",
      slug: "oracle-secrets",
      title: "Workshop",
      blocks: [{ id: "workshop-banner", type: "banner", content: "Workshop", subtitle: "Detail ukázkové akce.", ctaText: "Rezervovat", ctaHref: "/events/", bgImage: photo("workshop-page-1200x720.jpg") }],
    },
  ],
  siteSettings: {
    accentColor: "#7c3bb2",
    logoUrl: "/demo-assets/petra-logo.svg",
    metaTitle: "Petra Studio",
    metaDescription: "Profesionální demo šablona pro osobní služby, konzultace a digitální produkty.",
    customCss: "",
  },
};

export const asteraTemplate: TemplateDefinition = {
  key: "astera",
  name: "Petra Studio",
  industry: "consulting",
  version: "1.0.0",

  designTokens: {
    colorPrimary: "#7c3bb2",
    colorSecondary: "#5f2a8d",
    colorBackground: "#ffffff",
    colorSurface: "#f9f7f7",
    colorText: "#1f1f1f",
    colorTextMuted: "#2d2530",
    colorAccent: "#7c3bb2",
    colorBorder: "#dde5f0",
    fontHeading: "Playfair Display, serif",
    fontBody: "Poppins, sans-serif",
    borderRadius: "12px",
    spacing: "normal",
  },

  defaultSections: [
    { type: "astera-home", variant: "astera-web-home", order: 0, visible: true },
  ],

  demoContent: {
    siteName: "Petra Studio",
    tagline: "Profesionální demo šablona",
    description: "Fiktivní demo obsah pro jemnou konzultační šablonu ve Venom SaaS.",
    seo: {
      title: demoContent.siteSettings.metaTitle,
      description: demoContent.siteSettings.metaDescription,
      localBusiness: {
        type: "ProfessionalService",
        city: "Praha",
        region: "Hlavní město Praha",
      },
    },
    "astera-home": demoContent,
  },
};
