import { NextRequest, NextResponse } from "next/server";
import * as fs from "fs";
import * as path from "path";
import { query, initDb } from "@/lib/db";
import { addToReviewQueue, logProgress } from "@/lib/template-lab/workflow";

// POST /api/template-lab/import
// Import file-system templates into the DB (for templates generated by the standalone script)
export async function POST(req: NextRequest) {
  await initDb();

  const generatedDir = path.join(process.cwd(), "template-lab", "generated");
  if (!fs.existsSync(generatedDir)) {
    return NextResponse.json({ error: "No generated directory found" }, { status: 404 });
  }

  const imported: string[] = [];
  const skipped: string[] = [];
  const errors: string[] = [];

  const industries = fs.readdirSync(generatedDir).filter((d) =>
    fs.statSync(path.join(generatedDir, d)).isDirectory()
  );

  for (const industry of industries) {
    const industryDir = path.join(generatedDir, industry);
    const templateDirs = fs.readdirSync(industryDir).filter((d) =>
      fs.statSync(path.join(industryDir, d)).isDirectory()
    );

    for (const templateSlug of templateDirs) {
      const templateFile = path.join(industryDir, templateSlug, "template.json");
      if (!fs.existsSync(templateFile)) continue;

      // Check if already in DB
      const [existing] = await query<{ id: number }>(
        "SELECT id FROM template_lab_generated WHERE template_slug = $1",
        [templateSlug]
      );
      if (existing) {
        skipped.push(templateSlug);
        continue;
      }

      try {
        const templateData = JSON.parse(fs.readFileSync(templateFile, "utf-8"));
        const { slug, name, industry: tIndustry, sourceUrl, definition, generatedAt } = templateData;

        // Create a job record (no job_id column — just uses serial id)
        const [job] = await query<{ id: number }>(
          `INSERT INTO template_lab_jobs (url, industry, status, stage, started_at, updated_at)
           VALUES ($1, $2, 'completed', 'complete', $3, now())
           RETURNING id`,
          [sourceUrl, tIndustry, generatedAt || new Date().toISOString()]
        );

        // Determine research dir
        const domain = new URL(sourceUrl).hostname.replace(/^www\./, "");
        const screenshotDesktop = path.join(
          process.cwd(), "template-lab", "research", tIndustry, domain, "screenshots", "desktop.png"
        );
        const screenshotMobile = path.join(
          process.cwd(), "template-lab", "research", tIndustry, domain, "screenshots", "mobile.png"
        );

        await query(
          `INSERT INTO template_lab_generated
             (job_id, template_slug, template_name, industry, source_url, editable_schema, status, created_at, updated_at,
              preview_desktop, preview_mobile)
           VALUES ($1, $2, $3, $4, $5, $6, 'pending', $7, now(), $8, $9)`,
          [
            job?.id || null,
            slug,
            name,
            tIndustry,
            sourceUrl,
            JSON.stringify(definition),
            generatedAt || new Date().toISOString(),
            fs.existsSync(screenshotDesktop) ? screenshotDesktop : null,
            fs.existsSync(screenshotMobile) ? screenshotMobile : null,
          ]
        );

        // Add to review queue if screenshots exist
        addToReviewQueue({
          jobId: `import-${job?.id || Date.now()}`,
          templateSlug: slug,
          templateName: name,
          industry: tIndustry,
          sourceUrl,
          screenshotDesktop: fs.existsSync(screenshotDesktop) ? screenshotDesktop : undefined,
          screenshotMobile: fs.existsSync(screenshotMobile) ? screenshotMobile : undefined,
        });

        logProgress(`📥 Imported template from filesystem: ${slug}`);
        imported.push(slug);
      } catch (err) {
        errors.push(`${templateSlug}: ${String(err)}`);
      }
    }
  }

  return NextResponse.json({ imported, skipped, errors });
}
