"use client";

import { useEffect, useState, useMemo } from "react";

interface TenantRow {
  id: number;
  slug: string;
  email: string;
  template_id: number | null;
  lifecycle_status: string;
  created_at: string;
  sections_count: number;
  pages_count: number;
}

// Slugs that look like they were auto-generated by onboarding (word-XXXXX)
function isOnboardingSlug(slug: string) {
  return /^.+-[a-z0-9]{5}$/.test(slug);
}

// Slugs that are template/dev tenants (barber-01-v2, demo@*.test, etc.)
function isTemplateTenant(t: TenantRow) {
  return (
    t.email.endsWith(".test") ||
    t.email.endsWith("demo.local") ||
    t.slug.includes("-v2") ||
    t.slug.includes("-demo") ||
    t.slug.includes("-showcase") ||
    /^[a-z]+-\d{2}$/.test(t.slug)
  );
}

type FilterMode = "all" | "onboarding" | "templates";

export default function AdminTenantsPage() {
  const [tenants, setTenants] = useState<TenantRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<Set<number>>(new Set());
  const [filter, setFilter] = useState<FilterMode>("onboarding");
  const [search, setSearch] = useState("");
  const [deleting, setDeleting] = useState(false);
  const [lastDeleted, setLastDeleted] = useState<number | null>(null);

  useEffect(() => {
    fetch("/api/admin/tenants")
      .then(r => r.json())
      .then((d: { tenants: TenantRow[] }) => { setTenants(d.tenants ?? []); setLoading(false); })
      .catch(() => setLoading(false));
  }, []);

  const visible = useMemo(() => {
    let list = tenants;
    if (filter === "onboarding") list = list.filter(t => isOnboardingSlug(t.slug) && !isTemplateTenant(t));
    if (filter === "templates") list = list.filter(t => isTemplateTenant(t));
    if (search) list = list.filter(t => t.slug.includes(search) || t.email.includes(search));
    return list;
  }, [tenants, filter, search]);

  function toggleOne(id: number) {
    setSelected(prev => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  }

  function selectAll() {
    const visibleIds = visible.map(t => t.id);
    const allSelected = visibleIds.every(id => selected.has(id));
    if (allSelected) {
      setSelected(prev => { const n = new Set(prev); visibleIds.forEach(id => n.delete(id)); return n; });
    } else {
      setSelected(prev => { const n = new Set(prev); visibleIds.forEach(id => n.add(id)); return n; });
    }
  }

  async function handleDelete() {
    const ids = Array.from(selected);
    if (ids.length === 0) return;
    if (!confirm(`Smazat ${ids.length} tenantů? Tato akce je nevratná.`)) return;
    setDeleting(true);
    try {
      const r = await fetch("/api/admin/tenants", {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ ids }),
      });
      const d = await r.json() as { deleted: number };
      setLastDeleted(d.deleted);
      setTenants(prev => prev.filter(t => !selected.has(t.id)));
      setSelected(new Set());
    } catch {
      alert("Chyba při mazání.");
    } finally {
      setDeleting(false);
    }
  }

  const onboardingCount = tenants.filter(t => isOnboardingSlug(t.slug) && !isTemplateTenant(t)).length;
  const templateCount = tenants.filter(t => isTemplateTenant(t)).length;
  const totalSections = tenants.reduce((s, t) => s + t.sections_count, 0);

  if (loading) return (
    <div className="flex items-center justify-center h-64">
      <div className="w-6 h-6 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin" />
    </div>
  );

  const visibleIds = visible.map(t => t.id);
  const allVisibleSelected = visibleIds.length > 0 && visibleIds.every(id => selected.has(id));

  return (
    <div className="p-8">
      <div className="flex items-start justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-white">Správa tenantů</h1>
          <p className="text-sm text-gray-400 mt-1">
            Celkem {tenants.length} tenantů · {totalSections.toLocaleString()} sekcí v DB
            {" · "}<span className="text-yellow-400">{onboardingCount} onboarding testů</span>
            {" · "}<span className="text-blue-400">{templateCount} šablon</span>
          </p>
        </div>
        <div className="flex gap-3">
          {lastDeleted !== null && (
            <span className="text-sm text-emerald-400 self-center">✓ Smazáno {lastDeleted} tenantů</span>
          )}
          {selected.size > 0 && (
            <button
              onClick={handleDelete}
              disabled={deleting}
              className="px-4 py-2 bg-red-600 hover:bg-red-500 disabled:opacity-50 text-white text-sm font-semibold rounded-xl transition-colors"
            >
              {deleting ? "Mažu…" : `Smazat ${selected.size} vybraných`}
            </button>
          )}
        </div>
      </div>

      {/* Filters */}
      <div className="flex gap-3 mb-4">
        {([
          ["all", `Vše (${tenants.length})`],
          ["onboarding", `Onboarding testy (${onboardingCount})`],
          ["templates", `Šablony (${templateCount})`],
        ] as [FilterMode, string][]).map(([key, label]) => (
          <button
            key={key}
            onClick={() => setFilter(key)}
            className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${
              filter === key
                ? "bg-indigo-600 text-white"
                : "bg-gray-800 text-gray-400 hover:text-white"
            }`}
          >
            {label}
          </button>
        ))}
        <input
          type="text"
          placeholder="Filtr slug/email…"
          value={search}
          onChange={e => setSearch(e.target.value)}
          className="ml-auto px-3 py-1.5 bg-gray-800 border border-gray-700 text-white placeholder-gray-500 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 w-52"
        />
      </div>

      {/* Table */}
      <div className="bg-gray-900 rounded-2xl border border-gray-800 overflow-hidden">
        <div className="px-6 py-3 border-b border-gray-800 flex items-center gap-3">
          <input
            type="checkbox"
            checked={allVisibleSelected}
            onChange={selectAll}
            className="accent-indigo-500 w-4 h-4"
          />
          <span className="text-xs text-gray-400 uppercase font-medium">
            {visible.length} zobrazeno · {selected.size} vybráno
          </span>
        </div>
        <table className="w-full">
          <thead>
            <tr className="border-b border-gray-800 text-left text-xs font-medium text-gray-400 uppercase">
              <th className="px-4 py-3 w-8" />
              <th className="px-4 py-3">Slug</th>
              <th className="px-4 py-3">E-mail</th>
              <th className="px-4 py-3">Status</th>
              <th className="px-4 py-3">Sekce</th>
              <th className="px-4 py-3">Vytvořen</th>
              <th className="px-4 py-3">Demo</th>
            </tr>
          </thead>
          <tbody>
            {visible.map(t => (
              <tr
                key={t.id}
                onClick={() => toggleOne(t.id)}
                className={`border-b border-gray-800/50 cursor-pointer transition-colors ${
                  selected.has(t.id) ? "bg-red-950/30" : "hover:bg-gray-800/30"
                }`}
              >
                <td className="px-4 py-3">
                  <input
                    type="checkbox"
                    checked={selected.has(t.id)}
                    onChange={() => toggleOne(t.id)}
                    onClick={e => e.stopPropagation()}
                    className="accent-red-500 w-4 h-4"
                  />
                </td>
                <td className="px-4 py-3 font-mono text-sm text-white">{t.slug}</td>
                <td className="px-4 py-3 text-sm text-gray-400">{t.email}</td>
                <td className="px-4 py-3">
                  <span className={`px-2 py-0.5 rounded-full text-xs ${
                    t.lifecycle_status === "published" ? "bg-emerald-900/50 text-emerald-300" :
                    t.lifecycle_status === "active" ? "bg-blue-900/50 text-blue-300" :
                    "bg-gray-800 text-gray-400"
                  }`}>
                    {t.lifecycle_status}
                  </span>
                </td>
                <td className="px-4 py-3 text-sm text-gray-400">{t.sections_count}</td>
                <td className="px-4 py-3 text-sm text-gray-500">
                  {new Date(t.created_at).toLocaleDateString("cs-CZ")}
                </td>
                <td className="px-4 py-3">
                  <a
                    href={`/demo/${t.slug}`}
                    target="_blank"
                    onClick={e => e.stopPropagation()}
                    className="text-xs text-indigo-400 hover:text-indigo-300"
                  >
                    Zobrazit →
                  </a>
                </td>
              </tr>
            ))}
            {visible.length === 0 && (
              <tr>
                <td colSpan={7} className="px-6 py-12 text-center text-gray-500 text-sm">
                  Žádné záznamy.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
