import { chromium } from "playwright-core";
const OUT = "/private/tmp/claude-501/-Users-apple-DEV-CRM/4a00ae5a-b11c-461e-b4a9-9748d2b4fba7/scratchpad";
const browser = await chromium.launch({ executablePath: "/Users/apple/Library/Caches/ms-playwright/chromium_headless_shell-1223/chrome-headless-shell-mac-arm64/chrome-headless-shell" });
const ctx = await browser.newContext({ viewport: { width: 1600, height: 900 } });
const page = await ctx.newPage();
await page.goto("http://localhost:3015/demo/eshop-16-v2?ts=" + Date.now(), { waitUntil: "networkidle", timeout: 90000 });
await page.screenshot({ path: `${OUT}/es16-navbar.png` });
await page.hover(`button:has-text("Produkty")`);
await page.waitForTimeout(2000);
await page.screenshot({ path: `${OUT}/es16-mega.png` });
await page.hover(`.es16-mega-cat:has-text("Mléčné a chlazené")`);
await page.waitForTimeout(1500);
await page.screenshot({ path: `${OUT}/es16-mega-mlecne.png` });
const mob = await browser.newContext({ viewport: { width: 390, height: 844 } });
const mp = await mob.newPage();
await mp.goto("http://localhost:3015/demo/eshop-16-v2?ts=" + Date.now(), { waitUntil: "networkidle", timeout: 90000 });
await mp.screenshot({ path: `${OUT}/es16-mobile.png` });
await mp.click(`button[aria-label="Otevřít menu"]`);
await mp.waitForTimeout(1200);
await mp.screenshot({ path: `${OUT}/es16-mobile-menu.png` });
await browser.close(); console.log("done");
