import { chromium } from "playwright-core";
const OUT = "/private/tmp/claude-501/-Users-apple-DEV-CRM/7ec14c67-ee68-443c-861e-34e686cfd306/scratchpad";
const URL = "http://localhost:3015/demo/eshop-19-v2";
const browser = await chromium.launch({ executablePath: "/Users/apple/Library/Caches/ms-playwright/chromium_headless_shell-1223/chrome-headless-shell-mac-arm64/chrome-headless-shell" });
const ctx = await browser.newContext({ viewport: { width: 1600, height: 900 } });
const page = await ctx.newPage();
await page.goto(URL + "?ts=" + Date.now(), { waitUntil: "networkidle", timeout: 90000 });
await page.screenshot({ path: `${OUT}/es19-top.png` });
await page.hover(`.es19-navtab >> nth=0`);
await page.waitForTimeout(1500);
await page.screenshot({ path: `${OUT}/es19-mega.png` });
const mob = await browser.newContext({ viewport: { width: 390, height: 844 } });
const mp = await mob.newPage();
await mp.goto(URL + "?ts=" + Date.now(), { waitUntil: "networkidle", timeout: 90000 });
await mp.screenshot({ path: `${OUT}/es19-mobile.png` });
await mp.click(`button[aria-label="Otevřít menu"]`);
await mp.waitForTimeout(1200);
await mp.screenshot({ path: `${OUT}/es19-mobile-menu.png` });
await browser.close(); console.log("done");
