import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', args: ['--no-sandbox'], headless: true });
const page = await (await browser.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
const ext = []; const f404 = []; const errs = [];
page.on('request', req => { const u = req.url(); if(!u.startsWith('http://localhost')&&!u.startsWith('data:')) ext.push(u); });
page.on('response', r => { if(r.status()===404) f404.push(r.url()); });
page.on('console', m => { if(m.type()==='error') errs.push(m.text()); });
await page.goto('http://localhost:3015/demo/freja-demo', { waitUntil: 'networkidle', timeout: 40000 });
await page.waitForTimeout(2000);
await page.screenshot({ path: '/tmp/freja-demo-desktop.png' });
await page.screenshot({ path: 'public/preview-freja-demo.jpg' });
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: '/tmp/freja-demo-mobile.png' });
const html = await page.content();
const brand = (html.match(/freja\.cz/gi)||[]).length;
const track = (html.match(/googletagmanager|shopify\.com\/s\/files\/[0-9]/gi)||[]).length;
console.log(`Ext: ${ext.length} | 404: ${f404.length} | Errors: ${errs.length} | Brand: ${brand} | Shopify CDN: ${track}`);
if(f404.length) console.log('404s:', f404.slice(0,5));
if(errs.length) console.log('Errors:', errs.slice(0,3));
if(ext.length) console.log('Ext reqs:', ext.slice(0,5));
await browser.close();
