import type { Metadata } from "next";
import { CheckCircle2, TriangleAlert } from "lucide-react";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { prisma } from "@/lib/prisma";
import { verifyUnsubscribeToken, type UnsubscribeType } from "@/lib/unsubscribe";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Unsubscribe",
  robots: { index: false, follow: false },
};

type PageProps = {
  searchParams: { type?: string; id?: string; token?: string; typ?: string; t?: string };
};

async function performUnsubscribe(type: UnsubscribeType, id: string): Promise<boolean> {
  try {
    if (type === "pes") {
      await prisma.demand.update({ where: { id }, data: { status: "CLOSED" } });
      return true;
    }
    if (type === "newsletter") {
      await prisma.contact.update({ where: { id }, data: { status: "ARCHIVED" } });
      return true;
    }
    return false;
  } catch {
    return false;
  }
}

export default async function EnglishUnsubscribePage({ searchParams }: PageProps) {
  // Accept both the English parameter names and existing links generated by the
  // Czech mailer, so switching language never invalidates an unsubscribe token.
  const rawType = searchParams.type ?? searchParams.typ;
  const id = searchParams.id;
  const token = searchParams.token ?? searchParams.t;
  const type = (rawType === "pes" || rawType === "newsletter" ? rawType : null) as UnsubscribeType | null;
  const valid = Boolean(type && id && token && verifyUnsubscribeToken(type!, id!, token!));
  const done = valid ? await performUnsubscribe(type!, id!) : false;

  return (
    <>
      <Header variant="solid" locale="en" />
      <main className="flex min-h-[70vh] items-center pt-16">
        <div className="mx-auto flex w-full max-w-xl flex-col items-center px-6 py-24 text-center">
          {done ? (
            <>
              <CheckCircle2 size={44} strokeWidth={1.2} className="text-bronze" />
              <h1 className="mt-6 text-[clamp(1.6rem,3vw,2.3rem)] font-semibold leading-[1.15] tracking-[-0.02em]">
                {type === "pes" ? "Your property alert has been cancelled" : "You have been unsubscribed"}
              </h1>
              <p className="mt-4 text-[15px] leading-[1.75] text-muted">
                We will not send you any further emails. You can subscribe again at any time on our website.
              </p>
            </>
          ) : (
            <>
              <TriangleAlert size={44} strokeWidth={1.2} className="text-bronze" />
              <h1 className="mt-6 text-[clamp(1.6rem,3vw,2.3rem)] font-semibold leading-[1.15] tracking-[-0.02em]">
                This link is not valid
              </h1>
              <p className="mt-4 text-[15px] leading-[1.75] text-muted">
                The unsubscribe link is incomplete or has already been used. Email info@ceskypartner.cz and our team will take care of it for you.
              </p>
            </>
          )}
          <a
            href="/en"
            className="mt-10 border border-ink px-8 py-3.5 text-[12.5px] font-semibold uppercase tracking-[0.16em] transition-colors duration-300 hover:bg-ink hover:text-paper"
          >
            Back to home
          </a>
        </div>
      </main>
      <Footer locale="en" />
    </>
  );
}
