import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Venom — Výběr šablon",
  robots: { index: false, follow: false },
};

const BASE = process.env.NEXT_PUBLIC_BASE_URL ?? "http://localhost:3015";

const TEMPLATES = [
  {
    slug: "peak-cut-demo",
    name: "Peak Cut",
    origin: "barbershop-buddy.cz",
    category: "Barbershop",
    token: "peak7yu76p11q1",
    status: "live" as const,
    color: "#1a1a1a",
    accent: "#d4a96e",
    screenshot: "/preview-peak-cut.jpg",
    desc: "Minimalistický barbershop s tmavým designem, hero foto, ceníkem a galerií.",
  },
  {
    slug: "the-barber-demo",
    name: "The Barber",
    origin: "thebarber.cz",
    category: "Barbershop",
    token: "barberp6pj2jrgtd",
    status: "live" as const,
    color: "#111",
    accent: "#d4a96e",
    screenshot: "/preview-the-barber.jpg",
    desc: "Prémiový barbershop s B&W fotografiemi, 4-sloupcovou galerií a pricing sekcí.",
  },
  {
    slug: "fade-room-demo",
    name: "Barber Urban",
    origin: "barbershopurban.cz",
    category: "Barbershop",
    token: "ed1t9rjb8lyyew84198c",
    status: "live" as const,
    color: "#1c1410",
    accent: "#c8a96e",
    screenshot: "/preview-barber-urban.jpg",
    desc: "Luxusní barbershop s warm golden lighting, koženými křesly a elegantním minimalistickým designem.",
  },
  {
    slug: "barber-praha-demo",
    name: "Barber Praha",
    origin: "barberpraha.online",
    category: "Barbershop",
    token: "bprahafro9zflo",
    status: "live" as const,
    color: "#1a1a1a",
    accent: "#c8972a",
    screenshot: "/preview-barber-praha.jpg",
    desc: "Prémiový WordPress/Divi barbershop s týmem, galerií, ceníkem a plnohodnotným hero sectionem.",
  },
  {
    slug: "studio-jarka-demo",
    name: "Studio Jarka",
    origin: "jarkacechova.cz",
    category: "Kadeřnictví",
    token: "stujarkasssjelf5",
    status: "live" as const,
    color: "#8A6F28",
    accent: "#c8a96e",
    screenshot: "/preview-studio-jarka.jpg",
    desc: "Luxusní kadeřnický salon — Tilda CMS, T396 zero-blocks, tým 7 stylistek, recenze, kontakty.",
  },
  {
    slug: "hairsalon-no1-demo",
    name: "Hair Studio No.1",
    origin: "hairsalon-no1.cz",
    category: "Kadeřnictví",
    token: "no1hair8ahh4had4o",
    status: "live" as const,
    color: "#1a1a1a",
    accent: "#c8a97e",
    screenshot: "/preview-hairsalon-no1.jpg",
    desc: "Prémiový vlasový salon — WordPress/Flatsome, hero slider, tým, galerie, vitamíny, recenze.",
  },
  {
    slug: "petramechurova-demo",
    name: "Petra Studio",
    origin: "petramechurova.cz",
    category: "Kadeřnictví",
    token: "petra3wv4i7e0ho",
    status: "live" as const,
    color: "#2f201a",
    accent: "#c8a97e",
    screenshot: "/preview-petramechurova.jpg",
    desc: "Luxusní prémiový salon — Weblantis CMS, Bootstrap 5, hero, tým, blog, galerie, kolekce.",
  },
  {
    slug: "selfbeauty-demo",
    name: "Demo Beauty Studio",
    origin: "selfbeautystudio.com",
    category: "Beauty & Wellness",
    token: "selfbp0hr6nllun",
    status: "live" as const,
    color: "#1a1a1a",
    accent: "#c9a96e",
    screenshot: "/preview-selfbeauty-demo.jpg",
    desc: "Full-stack beauty studio — WIX Thunderbolt klon, 5 stránek: domů, barbershop ceník, manikúra, kosmetika, voucher.",
  },
  {
    slug: "praha-masaze-demo",
    name: "Demo Masáže",
    origin: "prahamasaze.com",
    category: "Masáže & Wellness",
    token: "masazemfg4pp1l",
    status: "live" as const,
    color: "#2d1f14",
    accent: "#8b6f47",
    screenshot: "/preview-praha-masaze-demo.jpg",
    desc: "Masážní salon — WordPress/GeneratePress, 3 stránky: domů, ceník, rezervace. Klasická, sportovní, thajská masáž.",
  },
  {
    slug: "ananda-demo",
    name: "Demo Ananda SPA",
    origin: "anandaspa.cz",
    category: "Ayurvéda & Wellness",
    token: "anandaar4r2nv26",
    status: "live" as const,
    color: "#2a1a0a",
    accent: "#b8943f",
    screenshot: "/preview-ananda-demo.jpg",
    desc: "Luxusní Ayurvédické SPA — Laravel+Alpine+Vite, 3 stránky: domů, procedury, dárkový voucher. Zlaté akcenty, hero slider.",
  },
  {
    slug: "tawan-demo",
    name: "Demo TAWAN Masáže",
    origin: "tawan.cz",
    category: "Thajské masáže",
    token: "tawanv0ki4mwra",
    status: "live" as const,
    color: "#0a0a0a",
    accent: "#c8a96e",
    screenshot: "/preview-tawan-demo.jpg",
    desc: "Luxusní thajský masážní salon — Drupal CMS, 4 stránky: domů, masáže, ceník, dárkový voucher. Tmavý design, zlaté akcenty.",
  },
  {
    slug: "escape-demo",
    name: "Demo Escape Massage",
    origin: "escapemassage.cz",
    category: "Thajské masáže",
    token: "escapea82eja0nx",
    status: "live" as const,
    color: "#f5ede4",
    accent: "#b8943f",
    screenshot: "/preview-escape-demo.jpg",
    desc: "Thajský masážní salon Praha — WordPress/WPO-Minify, 4 stránky: domů, masáže, ceník, dárkový voucher. Krémový design, zlaté akcenty.",
  },
  {
    slug: "tribo-demo",
    name: "Demo TRIBO Studio",
    origin: "tribo.cz",
    category: "Tetování & Piercing",
    token: "tribochcnp2al5",
    status: "live" as const,
    color: "#111111",
    accent: "#e0c070",
    screenshot: "/preview-tribo-demo.jpg",
    desc: "Tetovací studio — Solid Pixels CMS, 4 stránky: domů, tattoo, ceník, kontakt. Tmavý design, hero foto rukou.",
  },
  {
    slug: "homie-demo",
    name: "Demo Homie Tattoo",
    origin: "homietattoo.cz",
    category: "Tetování & Piercing",
    token: "homiepjd4pwgl2",
    status: "live" as const,
    color: "#1a1a1a",
    accent: "#e0c070",
    screenshot: "/preview-homie-demo.jpg",
    desc: "Prémiové tetovací & piercing studio — WordPress/Webflow, 3 stránky: domů, piercing, FAQ. Tmavý design, hero salon foto.",
  },
  {
    slug: "magic-demo",
    name: "Demo Magic Tattoo",
    origin: "magictattoo.cz",
    category: "Tetování & Piercing",
    token: "magic835ypgo7su",
    status: "live" as const,
    color: "#0a0a0a",
    accent: "#e03030",
    screenshot: "/preview-magic-demo.jpg",
    desc: "Walk-in tetovací studio Praha — WordPress/Bricks Builder, 3 stránky: domů, ceník, FAQ. Tmavý design, hero tým foto, červené akcenty.",
  },
  {
    slug: "soho-demo",
    name: "Demo Soho Nails & Spa",
    origin: "sohosalon.cz",
    category: "Nehtové studio",
    token: "sohoc6mppfq2",
    status: "live" as const,
    color: "#5c1a1a",
    accent: "#d4a0a0",
    screenshot: "/preview-soho-demo.jpg",
    desc: "Nehtové studio & spa Praha — WordPress/Divi, 3 stránky: domů, ceník, o salonu. Tmavý višňový design, elegantní hero slider, EN/UA lokalizace.",
  },
  {
    slug: "celebrate-demo",
    name: "Demo Celebrate Salon",
    origin: "celebratesalon.cz",
    category: "Nehtové studio",
    token: "celebrate80nw5a8o",
    status: "live" as const,
    color: "#6b3f38",
    accent: "#d4a080",
    screenshot: "/preview-celebrate-demo.jpg",
    desc: "Nehtové studio Praha — Wix Thunderbolt, 3 stránky: domů, manikúra, o nás. Tmavý vinový design, elegantní CTA, promo banner.",
  },
  {
    slug: "maidenstudio-demo",
    name: "Demo Maiden Studio",
    origin: "maidenstudio.cz",
    category: "Nehtové studio",
    token: "maidenyj9jtvw3",
    status: "live" as const,
    color: "#f5ede8",
    accent: "#8b6550",
    screenshot: "/preview-maidenstudio-demo.jpg",
    desc: "Nehtové a kosmetické studio Praha — Wix Thunderbolt, 3 stránky: domů, manikúra, o nás. Světlý design, hero tým foto, OBJEDNAT SE CTA.",
  },
  {
    slug: "esthesia-demo",
    name: "Demo Esthesia Clinic",
    origin: "esthesia.cz",
    category: "Kosmetická klinika",
    token: "esthesiagcrx0kq9",
    status: "live" as const,
    color: "#f5ede8",
    accent: "#c8a070",
    screenshot: "/preview-esthesia-demo.jpg",
    desc: "Prémiová kosmetická klinika Praha — WordPress/Elementor (luchiana theme), 3 stránky: domů, ceník, kontakt. Světlý design, hero slider s procedurami.",
  },
  {
    slug: "bomton-demo",
    name: "Demo Bomton Clinic",
    origin: "bomtonclinic.cz",
    category: "Kosmetická klinika",
    token: "bomtonjpfyxhdh",
    status: "live" as const,
    color: "#f5f0eb",
    accent: "#b8943f",
    screenshot: "/preview-bomton-demo.jpg",
    desc: "Prémiová kosmetická klinika Praha — Wix Thunderbolt, 2 stránky: domů, o klinice. Světlý design, hero injekce foto.",
  },
  {
    slug: "yesvisage-demo",
    name: "Demo Yes Visage",
    origin: "yesvisage.cz",
    category: "Kosmetická klinika",
    token: "yesvisageixenj48u",
    status: "live" as const,
    color: "#1a1a1a",
    accent: "#c8a96e",
    screenshot: "/preview-yesvisage-demo.jpg",
    desc: "Prémiová kosmetická klinika Praha — WordPress/ipress theme, 3 stránky: domů, ceník, kontakt. Temný design, hero slider.",
  },
  {
    slug: "linda-demo",
    name: "Demo Linda Sikorová",
    origin: "lindasikorova.com",
    category: "Fitness & Wellness",
    token: "lindamzy0cgcq",
    status: "live" as const,
    color: "#c8a98e",
    accent: "#8b6f47",
    screenshot: "/preview-linda-demo.jpg",
    desc: "Fyzioterapeut & osobní trenér Praha — WordPress/Elementor Hello, 1-stránkový web s ceníkem, recenzemi, FAQ a kontaktem.",
  },
  {
    slug: "victory-demo",
    name: "Demo Fitness Victory",
    origin: "fitnessvictory.cz",
    category: "Fitness & Wellness",
    token: "victoryv1qzyya1",
    status: "live" as const,
    color: "#0d0d0d",
    accent: "#c800c8",
    screenshot: "/preview-victory-demo.jpg",
    desc: "Moderní fitness centrum Praha — WordPress/Elementor, 3 stránky: domů, skupinové lekce, kontakt. Tmavý design, hero foto posilovny, ružové akcenty.",
  },
  {
    slug: "fyziovsem-demo",
    name: "Demo Fyzio Všem",
    origin: "fyziovsem.cz",
    category: "Fyzioterapie",
    token: "fyziovsemkf5jpr4z",
    status: "live" as const,
    color: "#1a3a2a",
    accent: "#4a9a6a",
    screenshot: "/preview-fyziovsem-demo.jpg",
    desc: "Fyzioterapeutická klinika Praha — WordPress/OceanWP+Elementor, 3 stránky: domů, služby, tým. Zelený design, hero foto.",
  },
  {
    slug: "resetclinic-demo",
    name: "Demo Reset Fyzio",
    origin: "resetclinic.cz",
    category: "Fyzioterapie",
    token: "resetclinic9be78iun",
    status: "live" as const,
    color: "#0a1a2a",
    accent: "#4a8ab0",
    screenshot: "/preview-resetclinic-demo.jpg",
    desc: "Sportovní fyzioterapie Praha — Webflow, 3 stránky: domů, terapie, tým. Modrý design, hero sekce.",
  },
  {
    slug: "ambi-bistro-demo",
    name: "Demo Ambiente Bistro",
    origin: "ambi.cz",
    category: "Restaurace",
    token: "ambia1m94rby",
    status: "live" as const,
    color: "#1a0e0a",
    accent: "#c8943f",
    screenshot: "/preview-ambi-bistro-demo.jpg",
    desc: "Prémiová restaurace Praha — Astro SSG + Contember CMS, 4 stránky: domů, menu, rezervace, o nás. Tmavý luxusní design.",
  },
  {
    slug: "hybernska-demo",
    name: "Demo Hybernská",
    origin: "restauracehybernska.cz",
    category: "Restaurace",
    token: "hybernska2irczfr2",
    status: "live" as const,
    color: "#1a1208",
    accent: "#c8a040",
    screenshot: "/preview-hybernska-demo.jpg",
    desc: "Česká restaurace Praha — Shoptet CMS, 4 stránky: domů, menu, o nás, kontakt. Světlý design, hero foto.",
  },
  {
    slug: "lacasa-latina-demo",
    name: "Demo La Casa Latina",
    origin: "lacasalatina.cz",
    category: "Restaurace",
    token: "lacasamve6r3jw",
    status: "live" as const,
    color: "#2a0a0a",
    accent: "#d04030",
    screenshot: "/preview-lacasa-latina-demo.jpg",
    desc: "Latino fusion restaurace Praha — WordPress + WPBakery + Webox, 4 stránky: domů, o nás, menu, galerie. Červený design.",
  },
  {
    slug: "cafe-savoy-demo",
    name: "Demo Café Savoy",
    origin: "cafesavoy.ambi.cz",
    category: "Kavárna",
    token: "cafesavoya7y7pizr",
    status: "live" as const,
    color: "#1a1208",
    accent: "#c8a040",
    screenshot: "/preview-cafe-savoy-demo.jpg",
    desc: "Vídeňská kavárna Praha — Astro SSG + Contember CMS, 3 stránky: domů, menu, rezervace. Elegantní design.",
  },
  {
    slug: "zrno-zrnko-demo",
    name: "Demo Zrno Zrnko",
    origin: "zrnozrnko.cz",
    category: "Pekárna & Kavárna",
    token: "zrnkorrymswo8",
    status: "live" as const,
    color: "#1a1208",
    accent: "#8b6030",
    screenshot: "/preview-zrno-zrnko-demo.jpg",
    desc: "Řemeslná pekárna & kavárna Praha Nusle — Webnode 2, 4 stránky: domů, o nás, pekárna, káva. Světlý design.",
  },
  {
    slug: "costa-coffee-demo",
    name: "Demo Costa Coffee",
    origin: "costa-coffee.cz",
    category: "Kavárenský řetězec",
    token: "costa7dbsn7qg",
    status: "live" as const,
    color: "#7a1818",
    accent: "#e8c8a8",
    screenshot: "/preview-costa-coffee-demo.jpg",
    desc: "Mezinárodní kavárenský řetězec — WordPress custom theme, 4 stránky: domů, nabídka, kavárny, historie. Červený brand design.",
  },
  {
    slug: "coffee-room-demo",
    name: "Demo Coffee Room",
    origin: "coffeeroom.cz",
    category: "Specialty kavárna",
    token: "coffeeroomz3whnx56",
    status: "live" as const,
    color: "#1a1a1a",
    accent: "#b8945f",
    screenshot: "/preview-coffee-room-demo.jpg",
    desc: "Specialty kavárna Praha — Webflow CMS, 4 stránky: domů, menu, kontakt, obchod. Minimalistický design s velkou hero fotkou.",
  },
  {
    slug: "cathedral-cafe-demo",
    name: "Demo Cathedral Café",
    origin: "cathedralcafe.cz",
    category: "Kavárna & Restaurace",
    token: "cathedralitnpkbn7",
    status: "live" as const,
    color: "#0f3020",
    accent: "#c8a060",
    screenshot: "/preview-cathedral-cafe-demo.jpg",
    desc: "Kavárna & restaurace v centru Prahy — Stimulus + Swup, 4 stránky: domů, menu, galerie, kontakt. Zelený design s hero foto letní zahrady.",
  },
  {
    slug: "lexxus-norton-demo",
    name: "Demo Lexxus Norton",
    origin: "lexxusnorton.cz",
    category: "Realitní kancelář",
    token: "lexxus3uxrrkdg",
    status: "live" as const,
    color: "#1a3640",
    accent: "#d4a96e",
    screenshot: "/preview-lexxus-norton-demo.jpg",
    desc: "Prémiová realitní kancelář Praha — Next.js SSR, 4 stránky: domů, o nás, kontakt, oblíbené nemovitosti. Luxusní tmavě modrý design.",
  },
  {
    slug: "fer-makleri-demo",
    name: "Demo FER Makléři",
    origin: "fermakleri.cz",
    category: "Realitní kancelář",
    token: "fer5eeitvze",
    status: "live" as const,
    color: "#0f4630",
    accent: "#3cc88a",
    screenshot: "/preview-fer-makleri-demo.jpg",
    desc: "Online porovnávač realitních makléřů — Custom PHP, 4 stránky: domů, o nás, kontakt, pro makléře. Zelený moderní design.",
  },
  {
    slug: "reality-skutovi-demo",
    name: "Demo Reality Škutovi",
    origin: "realityskutovi.cz",
    category: "Realitní kancelář",
    token: "skutovio27vy0z6",
    status: "live" as const,
    color: "#2a1810",
    accent: "#c8a060",
    screenshot: "/preview-reality-skutovi-demo.jpg",
    desc: "Rodinná realitní kancelář Ústí nad Labem — Webflow CMS, 4 stránky: domů, prodej, pronájem, kontakt. Teplé barvy, podzimní design.",
  },
  {
    slug: "quantum-reality-demo",
    name: "Demo Quantum Reality",
    origin: "quantumreality.cz",
    category: "Realitní kancelář",
    token: "quantumum2rbo5m",
    status: "live" as const,
    color: "#0a1820",
    accent: "#33b3a0",
    screenshot: "/preview-quantum-reality-demo.jpg",
    desc: "Realitní kancelář Praha — WordPress + custom theme, 4 stránky: domů, o nás, kontakty, hypoteční centrum. Tyrkysové akcenty, dual-CTA hero.",
  },
  {
    slug: "jan-srubar-demo",
    name: "Demo Jan Šrubař",
    origin: "jansrubar.cz",
    category: "Realitní makléř",
    token: "srubarele36io4",
    status: "live" as const,
    color: "#1a2530",
    accent: "#3a5878",
    screenshot: "/preview-jan-srubar-demo.jpg",
    desc: "Osobní realitní makléř Praha — Next.js SSR na Vercel, 4 stránky: domů, o mně, služby, kontakt. Profesionální fotka makléře, recenze Google.",
  },
  {
    slug: "ondrej-kucera-demo",
    name: "Demo Ondřej Kučera",
    origin: "ondrejkucera.com",
    category: "Realitní makléř",
    token: "okucera9ziclrrh",
    status: "live" as const,
    color: "#0a0a0a",
    accent: "#c8a060",
    screenshot: "/preview-ondrej-kucera-demo.jpg",
    desc: "Osobní realitní makléř Praha — Custom CMS, 4 stránky: domů, o mně, jak na to, kontakt. Tmavý prémiový design se zlatými akcenty, awards.",
  },
  {
    slug: "best-drive-demo",
    name: "Demo BestDrive",
    origin: "bestdrive.cz",
    category: "Autoservis & Pneuservis",
    token: "bdz960921h",
    status: "live" as const,
    color: "#1a1a1a",
    accent: "#f5a623",
    screenshot: "/preview-best-drive-demo.jpg",
    desc: "Autoservis & pneuservis řetězec — Adobe AEM, 4 stránky: domů, prodejny, akce, pneuservis. Oranžový brand design Continental BestDrive.",
  },
  {
    slug: "autoservis-garant-demo",
    name: "Demo Autoservis GARANT",
    origin: "autoservis-garant.cz",
    category: "Autoservis",
    token: "garcjptpniq",
    status: "live" as const,
    color: "#1a1a1a",
    accent: "#d3252b",
    screenshot: "/preview-autoservis-garant-demo.jpg",
    desc: "Autoservis Praha — WordPress + carservice theme, 4 stránky: domů, o nás, kontakt, reference. Červený design, multilanguage.",
  },
  {
    slug: "autoservis-tomas-demo",
    name: "Demo Autoservis Tomáš",
    origin: "autoservistomas.cz",
    category: "Autoservis BMW",
    token: "tomas4z0cwisz",
    status: "live" as const,
    color: "#0a0a0a",
    accent: "#f56500",
    screenshot: "/preview-autoservis-tomas-demo.jpg",
    desc: "Specializovaný BMW autoservis & pneuservis — React SPA na Netlify, 1 onepage: hero, služby, ceník, galerie, kontakt. Tmavý design, oranžový akcent.",
  },
  {
    slug: "magic-smile-demo",
    name: "Demo Magic Smile",
    origin: "magicsmile.cz",
    category: "Zubní klinika",
    token: "magicl47kwe7f",
    status: "live" as const,
    color: "#0a2a4a",
    accent: "#28a0c8",
    screenshot: "/preview-magic-smile-demo.jpg",
    desc: "Stomatologická klinika Praha — WordPress + Orion7 theme, 4 stránky: domů, o nás, služby, kontakty. Modrý design, hero foto kliniky.",
  },
  {
    slug: "svet-rovnatek-demo",
    name: "Demo Svět rovnátek",
    origin: "svetrovnatek.cz",
    category: "Ortodoncie",
    token: "svet2hu3lv3e",
    status: "live" as const,
    color: "#1a3030",
    accent: "#3ab0a0",
    screenshot: "/preview-svet-rovnatek-demo.jpg",
    desc: "Neviditelná rovnátka Praha & Brno — Webflow CMS, 4 stránky: domů, rovnátka, financování, kontakt. Zelený design, žena s úsměvem, Google 4.8★.",
  },
  {
    slug: "perfect-smile-demo",
    name: "Demo Perfect Smile",
    origin: "perfect-smile.cz",
    category: "Ortodoncie",
    token: "psu2yfoz2z",
    status: "live" as const,
    color: "#3a1a1a",
    accent: "#c8a0a0",
    screenshot: "/preview-perfect-smile-demo.jpg",
    desc: "Ortodontická klinika Praha — Custom PHP CMS, 4 stránky: domů, služby, reference, kontakty. Rose-pink design, video hero, rovnátka pro dospělé.",
  },
  {
    slug: "havel-partners-demo",
    name: "Demo HAVEL & PARTNERS",
    origin: "havelpartners.cz",
    category: "Advokátní kancelář",
    token: "havelaqt0d7nu",
    status: "live" as const,
    color: "#0a1a3a",
    accent: "#c8a060",
    screenshot: "/preview-havel-partners-demo.jpg",
    desc: "Největší česko-slovenská advokátní kancelář — WordPress + Oxygen Builder, 4 stránky: domů, o nás, tým, kontakt. Tmavě modrý prémiový design.",
  },
  {
    slug: "rowan-legal-demo",
    name: "Demo ROWAN LEGAL",
    origin: "rowan.legal",
    category: "Advokátní kancelář",
    token: "rowan5kq2svte",
    status: "live" as const,
    color: "#1a2a5a",
    accent: "#e84024",
    screenshot: "/preview-rowan-legal-demo.jpg",
    desc: "Advokátní kancelář Praha — WordPress Bedrock + custom theme, 4 stránky: domů, o nás, služby, kontakty. Oranžovo-modrý design, video hero.",
  },
  {
    slug: "stavbadesign-demo",
    name: "Demo Stavba Design",
    origin: "stavbadesign.cz",
    category: "Stavební firma",
    token: "stavbaoz8g6oda",
    status: "live" as const,
    color: "#1a1a1a",
    accent: "#f05a00",
    screenshot: "/preview-stavbadesign-demo.jpg",
    desc: "Stavební firma Praha — WordPress Bedrock + Vite, 4 stránky: domů, služby, reference, kontakt. Bílý design s oranžovým akcentem.",
  },
  {
    slug: "baurekstav-demo",
    name: "Demo BauRekStav",
    origin: "baurekstav.cz",
    category: "Rekonstrukce bytů",
    token: "baurekgutd17y6",
    status: "live" as const,
    color: "#0e2b5c",
    accent: "#f05a00",
    screenshot: "/preview-baurekstav-demo.jpg",
    desc: "Rekonstrukce bytů Praha — statický HTML, 4 stránky: domů, služby, projekty, kontakt. Hero slider s fotkou interiéru, oranžový akcentní design.",
  },
  {
    slug: "bytyjadra-demo",
    name: "Demo Byty Jadra",
    origin: "bytyjadra.cz",
    category: "Rekonstrukce bytů",
    token: "bytyjadrawg47km",
    status: "live" as const,
    color: "#3d2b1f",
    accent: "#8b6043",
    screenshot: "/preview-bytyjadra-demo.jpg",
    desc: "Rekonstrukce bytů Praha — Next.js, 4 stránky: domů, činnosti, reference, kontakt. Hero s fotkou kuchyně, béžovo-hnědý design.",
  },
  {
    slug: "elektrobohacek-demo",
    name: "Demo Elektro Boháček",
    origin: "elektro-bohacek.cz",
    category: "Elektroinstalace",
    token: "elektro4die0138",
    status: "live" as const,
    color: "#1a0000",
    accent: "#cc0000",
    screenshot: "/preview-elektrobohacek-demo.jpg",
    desc: "Elektroinstalace Praha — WordPress + Elementor, 3 stránky: domů, elektroinstalace, hromosvody. Hero s fotkou elektrikáře, červený akcentní design.",
  },
  {
    slug: "instalateritopenari-demo",
    name: "Demo Instalatéři Praha",
    origin: "instalateritopenari.cz",
    category: "Instalatérství",
    token: "instalater9isc03",
    status: "live" as const,
    color: "#1a1a0a",
    accent: "#f5c400",
    screenshot: "/preview-instalateritopenari-demo.jpg",
    desc: "Instalatérství Praha — WordPress Astra + Elementor, 4 stránky. Žlutý design, 500+ spokojených klientů, +420 608 288 777.",
  },
  {
    slug: "perfectcatering-demo",
    name: "Demo Catering Praha",
    origin: "perfectcatering.cz",
    category: "Catering & Gastronomie",
    token: "pcatu3x47ochj9m",
    status: "live" as const,
    color: "#1a3535",
    accent: "#c9a96e",
    screenshot: "/preview-perfectcatering-demo.jpg",
    desc: "Prémiová cateringová firma — Nuxt.js SSR, single-page anchor nav. Tmavý teal design, chef foto, food gallery, partner loga, kontaktní formulář.",
  },
  {
    slug: "freja-demo",
    name: "Demo Květinářství",
    origin: "freja.cz",
    category: "Květinářství & E-shop",
    token: "frejad50mahlrhaq",
    status: "live" as const,
    color: "#2d1a1a",
    accent: "#c97b8a",
    screenshot: "/preview-freja-demo.jpg",
    desc: "Shopify Květinářství — rozvoz Prahou, product grid s 8 produkty, collection carousel, recenze, Google Maps, footer.",
  },
  {
    slug: "ovocnysvetozor-demo",
    name: "Demo Světozor",
    origin: "ovocnysvetozor.cz",
    category: "Cukrárna & Pekárna",
    token: "svetozor364wy1ps",
    status: "live" as const,
    color: "#e30613",
    accent: "#c00010",
    screenshot: "/preview-ovocnysvetozor-demo.jpg",
    desc: "Joomla Gantry 5 — cukrárenský řetězec Praha, 14 poboček. Hero s food photography, 3 feature ikony, promo banner, O nás sekce s produkty, dark footer.",
  },
  {
    slug: "antoninova-demo",
    name: "Demo pekářství",
    origin: "antoninovopekarstvi.cz",
    category: "Pekárna & Kavárna",
    token: "antoninovayr5ns3rg",
    status: "live" as const,
    color: "#212e60",
    accent: "#4a5a9a",
    screenshot: "/preview-antoninova-demo.jpg",
    desc: "WordPress Marco theme + Vegas slider — 7 pekáren Praha. Full-screen tmavý hero Edison bulb, Pojďte dál mosaic, Wolt & Bolt sekce, pobočky grid, contact footer.",
  },
  {
    slug: "nobe-demo",
    name: "Demo autoškola",
    origin: "nobe.cz",
    category: "Autoškola",
    token: "nobe4rprsb9w",
    status: "live" as const,
    color: "#ff6600",
    accent: "#e55a00",
    screenshot: "/preview-nobe-demo.jpg",
    desc: "WordPress simonet theme — oranžová identity, 11 poboček po ČR, mascot koza, MetaSlider hero, online studovna, dárkový poukaz, instruktoři grid, ceník, novinky.",
  },
  {
    slug: "jipka-demo",
    name: "Demo Jazyková škola",
    origin: "jipka.cz",
    category: "Jazyková škola",
    token: "jipkako46p4rp",
    status: "live" as const,
    color: "#833ca3",
    accent: "#6a2d8a",
    screenshot: "/preview-jipka-demo.jpg",
    desc: "WordPress multisite Elementor — jazyková škola Praha, 7 jazyků, hero swiper slider, kurzy grid, lektoři, recenze, pobočky, footer. Fialový brand.",
  },
  {
    slug: "skolapopulo-demo",
    name: "Demo Akademie",
    category: "Doučování & vzdělávání",
    origin: "skolapopulo.cz",
    cms: "Next.js SSR",
    token: "skolapopuloKx9m2n",
    status: "live" as const,
    color: "#0e3d6e",
    accent: "#1a5fa8",
    screenshot: "/preview-skolapopulo-demo.jpg",
    desc: "Next.js SSR — prémiové doučování Praha, subjects grid, video sekce, mapa ČR, recenze, stats, mediální ocenění, CTA form, footer. Modrý brand.",
  },
  {
    slug: "scioles-demo",
    name: "Demo Kroužky",
    category: "Dětské kroužky & vzdělávání",
    origin: "scioles.cz",
    cms: "ASP.NET CMS",
    token: "scioles" + "demo",
    status: "live" as const,
    color: "#2d6a2d",
    accent: "#f5c200",
    screenshot: "/preview-scioles-demo.jpg",
    desc: "ASP.NET CMS — dobrodružné kroužky pro děti, hero s přírodou, checklist aktivit, team sekce, 5 lokalit, benefity, ceník, footer. Zelený brand.",
  },
  {
    slug: "veterinafenix-demo",
    name: "Demo Veterinární Klinika",
    category: "Veterinární klinika",
    origin: "veterinafenix.cz",
    cms: "WordPress + Elementor",
    token: "veterinafenixdemo",
    status: "live" as const,
    color: "#8b1a1a",
    accent: "#00897b",
    screenshot: "/preview-veterinafenix-demo.jpg",
    desc: "WordPress/Elementor — veterinární klinika Praha, hero slider PSI/KOČKY/SAVCI, tým lékařů, certifikáty ISFM, kontakty. Červeno-tyrkysový brand.",
  },
  {
    slug: "cutedogs-demo",
    name: "Demo Psí Salon",
    category: "Psí a kočičí grooming salon",
    origin: "cutedogs.cz",
    cms: "WordPress",
    token: "cutedogsdemo",
    status: "live" as const,
    color: "#2c2c2c",
    accent: "#c8a96e",
    screenshot: "/preview-cutedogs-demo.jpg",
    desc: "WordPress — prémiový psí & kočičí salon Praha, hero s logo a CTA, instagram galerie, ceník střihů, reservace, footer. Tmavý zlatý brand.",
  },
  {
    slug: "skolkapropejska-demo",
    name: "Demo Hotel pro psy",
    category: "Psí hotel & školka",
    origin: "skolkapropejska.cz",
    cms: "WordPress",
    token: "skolkapropejskademo",
    status: "live" as const,
    color: "#2d6e3e",
    accent: "#f5c200",
    screenshot: "/preview-skolkapropejska-demo.jpg",
    desc: "WordPress — psí hotel a školka Praha, maskot pes, 3 služby (hotel/školka/salon), Instagram galerie, novinky, kontakty. Zelený brand.",
  },
  {
    slug: "ucetnictvispravne-demo",
    name: "Demo Účetnictví",
    category: "Účetní firma & daňové poradenství",
    origin: "ucetnictvispravne.cz",
    cms: "WordPress + Elementor",
    token: "ucetnictvispravnedemo",
    status: "live" as const,
    color: "#1a365d",
    accent: "#4a90d9",
    screenshot: "/preview-ucetnictvispravne-demo.jpg",
    desc: "WordPress/Elementor — účetní firma Praha, hero sekce, 3 služby, reference klientů, blog, ceník, kontakty. Modrý korporátní brand.",
  },
  {
    slug: "grantex-demo",
    name: "Demo Daňový Poradce",
    category: "Daňové poradenství & účetnictví",
    origin: "grantex.cz",
    cms: "WordPress + Elementor",
    token: "grantexdemo",
    status: "live" as const,
    color: "#1a3a2a",
    accent: "#4ade80",
    screenshot: "/preview-grantex-demo.jpg",
    desc: "WordPress/Elementor — daňový poradce Praha, hero advisory office, reference klientů (logos), EET sekce, kontakty. Tmavě zelený brand.",
  },
  {
    slug: "gpf-demo",
    name: "Demo Hypoteční Poradce",
    category: "Hypoteční poradenství & finance",
    origin: "gpf.cz",
    cms: "Nuxt SSR",
    token: "gpfdemo",
    status: "live" as const,
    color: "#0a2540",
    accent: "#3b82f6",
    screenshot: "/preview-gpf-demo.jpg",
    desc: "Nuxt SSR — hypoteční poradce, hero s domem, 14 partnerských bank (SVG logy), FAQ, kalkulačka, poradci, kontakty. Tmavě modrý finanční brand.",
  },
  {
    slug: "brokerconsulting-demo",
    name: "Demo Finanční Poradce",
    category: "Finanční poradenství & investice",
    origin: "bcas.cz (brokerconsulting.cz redirect)",
    cms: "Custom NETservis",
    token: "brokerconsultingdemo",
    status: "live" as const,
    color: "#003366",
    accent: "#d4a96e",
    screenshot: "/preview-brokerconsulting-demo.jpg",
    desc: "Custom CMS — finanční poradce, hero, dceřiné firmy (investice, reality, kredit, franšíza), tým ambasadorů, kontakty. Tmavě modrý korporátní brand.",
  },
  {
    slug: "karesarch-demo",
    name: "Demo Arch",
    category: "Architektonický ateliér",
    origin: "karesarch.cz",
    cms: "TYPO3",
    token: "karesarchdemo",
    status: "live" as const,
    color: "#1a1a1a",
    accent: "#d4a96e",
    screenshot: "/preview-karesarch-demo.jpg",
    desc: "TYPO3 — architektonický ateliér Brno+Praha, hero, portfolio realizací vil, projekty, interiéry, ocenění, kontakty. Minimalistický funkcionalismus.",
  },
  {
    slug: "schlieger-demo",
    name: "Demo Solar",
    category: "Fotovoltaika & tepelná čerpadla",
    origin: "schlieger.cz",
    cms: "WordPress + Elementor",
    token: "schliegerdemo",
    status: "live" as const,
    color: "#222222",
    accent: "#ffaa00",
    screenshot: "/preview-schlieger-demo.jpg",
    desc: "WordPress/Elementor — fotovoltaika & tepelná čerpadla, hero, reference, mapa instalací CZ/DE/AT, kalkulačka, kontakty. Tmavý korporátní brand, oranžové akcenty.",
  },
  {
    slug: "cleancat-demo",
    name: "Demo Clean",
    category: "Úklidová firma & mytí oken",
    origin: "cleancat.cz",
    cms: "Custom CMS",
    token: "cleancatdemo",
    status: "live" as const,
    color: "#0a4a3a",
    accent: "#69be28",
    screenshot: "/preview-cleancat-demo.jpg",
    desc: "Custom CMS — úklidová firma Ostrava, hero, 4 sekce služeb (úklid, čištění, bezpečnost, vzdělávání), aktuality, kontakty. Zelený korporátní brand.",
  },
  {
    slug: "vestop-demo",
    name: "Demo Vestop",
    origin: "vestop.cz",
    category: "Topenářství & Instalatérství",
    token: "vestopr1wamg",
    status: "live" as const,
    color: "#1a1a1a",
    accent: "#e53030",
    screenshot: "/preview-vestop-demo.jpg",
    desc: "Topenářství a instalatérství — WordPress + WPML, 4 stránky: domů, služby, reference, kontakt. Černý design, červený akcent, hero fotka instalatéra.",
  },
  {
    slug: "pragoclima-demo",
    name: "Demo Pragoclima",
    origin: "pragoclima.cz",
    category: "Klimatizace & Tepelná čerpadla",
    token: "pragov9d46e",
    status: "live" as const,
    color: "#1a2a4a",
    accent: "#e53030",
    screenshot: "/preview-pragoclima-demo.jpg",
    desc: "Klimatizace a tepelná čerpadla — WordPress + custom theme, 4 stránky: domů, služby, katalog, kontakt. Hero slider s produkty Daikin, červeno-modrý design.",
  },
  {
    slug: "acheating-demo",
    name: "Demo AC-Heating",
    origin: "ac-heating.cz",
    category: "Tepelná čerpadla & Fotovoltaika",
    token: "acheat62j0m",
    status: "live" as const,
    color: "#0a1a0a",
    accent: "#f5a623",
    screenshot: "/preview-acheating-demo.jpg",
    desc: "Tepelná čerpadla a fotovoltaika — custom PHP CMS, 4 stránky: domů, produkty, reference, kontakt. Hero s rodinou, oranžový akcent, SCOP 5.62.",
  },
  {
    slug: "greensie-demo",
    name: "Demo Greensie",
    origin: "greensie.cz",
    category: "Fotovoltaika",
    token: "grnsaj3qmp",
    status: "live" as const,
    color: "#0a2a1a",
    accent: "#3a9a5a",
    screenshot: "/preview-greensie-demo.jpg",
    desc: "Fotovoltaika a energetická řešení — WordPress + Oxygen Builder, 4 stránky: domů, služby, reference, kontakt. Zelený design, solární panely, výkon v kWp.",
  },
  {
    slug: "supellex-demo",
    name: "Demo Supellex",
    origin: "supellex.cz",
    category: "Podlahy & E-shop",
    token: "spllxi0olao",
    status: "live" as const,
    color: "#1a3a1a",
    accent: "#2a7a2a",
    screenshot: "/preview-supellex-demo.jpg",
    desc: "Podlahy, koberce a dřevěné podlahy — custom PHP e-shop, 4 stránky: domů, dřevěné podlahy, o nás, kontakt. Zelený design, produktový slider, showrooomy.",
  },
  {
    slug: "petrovomalovani-demo",
    name: "Demo Petrovo malování",
    origin: "petrovomalovani.cz",
    category: "Malíř & Natěrač",
    token: "petrofvqpwz",
    status: "live" as const,
    color: "#1a1a2a",
    accent: "#d4a040",
    screenshot: "/preview-petrovomalovani-demo.jpg",
    desc: "Malíř a natěrač Praha — statický HTML, 4 stránky: domů, malování, reference, kontakt. Hero s fotkou ložnice, zlaté akcenty, benefity, FAQ, recenze.",
  },
  {
    slug: "klempirzprahy-demo",
    name: "Demo Klempíř z Prahy",
    origin: "klempirzprahy.cz",
    category: "Klempíř & Pokrývač",
    token: "klempqz37wt",
    status: "live" as const,
    color: "#1a2a3a",
    accent: "#4a8ab0",
    screenshot: "/preview-klempirzprahy-demo.jpg",
    desc: "Klempíř a pokrývač Praha — statický HTML, anchor-based nav, 2 stránky: domů, klempířské práce. Hero video background, historické opravy, 5.0★.",
  },
  {
    slug: "gerberra-demo",
    name: "Demo Gerberra",
    origin: "gerberra.cz",
    category: "Zahradnické služby",
    token: "gerbeifxwtx",
    status: "live" as const,
    color: "#1a2a0a",
    accent: "#5a8a20",
    screenshot: "/preview-gerberra-demo.jpg",
    desc: "Zahradnické služby Praha — custom static site, 4 stránky: domů, služby, galerie, kontakt. Hero s fotkou zahrady, before/after realizace, kontaktní formulář.",
  },
  {
    slug: "polgarden-demo",
    name: "Demo PolGarden",
    origin: "polgarden.cz",
    category: "Realizace zahrad",
    token: "polga8p3xru",
    status: "live" as const,
    color: "#0a1a0a",
    accent: "#6ab030",
    screenshot: "/preview-polgarden-demo.jpg",
    desc: "Realizace zahrad a zahradní architektura Praha — custom PHP, 4 stránky: domů, realizace, inspirace, kontakt. Hero s treetop foto, 30+ let zkušeností, 100+ klientů.",
  },
  {
    slug: "lesarb-demo",
    name: "Demo Lesarb",
    origin: "lesarb.cz",
    category: "Arboristika",
    token: "lesarb8rbed",
    status: "live" as const,
    color: "#1a2f1a",
    accent: "#4caf50",
    screenshot: "/preview-lesarb-demo.jpg",
    desc: "Lesnické a arboristické práce — MySuitu CMS, 4 stránky: domů, kácení stromů, péče o stromy, kontakt. Hero se slajdrem, certifikované služby, galerie.",
  },
  {
    slug: "modryzralok-demo",
    name: "Demo Modrý Žralok",
    origin: "modryzralok.cz",
    category: "Úklidové služby",
    token: "modryzy34e6",
    status: "live" as const,
    color: "#0a1a3a",
    accent: "#019DFF",
    screenshot: "/preview-modryzralok-demo.jpg",
    desc: "Profesionální úklidová firma Praha — Webflow, 5 stránek: domů, ceník, reference, kontakt, o nás. Moderní design, hero s fotografiemi, ceník služeb.",
  },
  {
    slug: "deratizace-demo",
    name: "Demo Deratizace",
    origin: "deratizacepraha.com",
    category: "Deratizace / DDD",
    token: "deratd5nq6",
    status: "live" as const,
    color: "#0d1b3e",
    accent: "#3a7bd5",
    screenshot: "/preview-deratizace-demo.jpg",
    desc: "Hubení škůdců — Vue SPA, 5 stránek: domů, služby, deratizace, ceník, o nás. Grid škůdců (11 druhů), blog sekce, profesionální modrý design.",
  },
  {
    slug: "chaletmilada-demo",
    name: "Demo Chalet",
    origin: "chaletmilada.cz",
    category: "Ubytování / Horská chata",
    token: "chaletcxq5",
    status: "live" as const,
    color: "#0d1e2e",
    accent: "#d4a96e",
    screenshot: "/preview-chaletmilada-demo.jpg",
    desc: "Horská chata Krkonoše — Joomla + YOOtheme, 4 stránky: domů, ubytování, aktivity, rezervace. Hero slider, kenburns efekt, tmavý prémiový design.",
  },
  {
    slug: "palacehotel-demo",
    name: "Demo Boutique Hotel",
    origin: "palacehotel.cz",
    category: "Boutique Hotel / Apartmány",
    token: "palacehotel36k435",
    status: "live" as const,
    color: "#3a3735",
    accent: "#b08c5f",
    screenshot: "/preview-palacehotel-demo.jpg",
    desc: "Luxusní pětihvězdičkový boutique hotel v centru Prahy — vlastní CMS, jedna stránka: domů. Tmavý elegantní design, hero s logo intro, jarní nabídka, dark mode.",
  },
  {
    slug: "malirstvibastar-demo",
    name: "Demo Malířství",
    origin: "malirstvi-bastar.cz",
    category: "Malíř / Natěrač (2. varianta)",
    token: "mbiyekif",
    status: "live" as const,
    color: "#1a2937",
    accent: "#ff7a45",
    screenshot: "/preview-malirstvibastar-demo.jpg",
    desc: "Profesionální malířství — statická HTML, jedna stránka: domů. Hero s fotem maliřského válečku, modrá+oranžová paleta, služby, ceník, galerie, kontakty.",
  },
  {
    slug: "hotelatlantis-demo",
    name: "Demo Hotel Atlantis",
    origin: "hotel-atlantis.cz",
    category: "Hotel & Wellness",
    token: "hotel0kbc",
    status: "live" as const,
    color: "#0a1a0a",
    accent: "#8fbc8f",
    screenshot: "/preview-hotelatlantis-demo.jpg",
    desc: "Hotel & wellness u Brněnské přehrady — Vite SPA, 6 stránek: domů, ubytování, wellness, galerie, ceník, kontakt. Aerial hero foto, pokoje, balíčky.",
  },
  {
    slug: "zbiralova-demo",
    name: "Demo Fotografka",
    origin: "zbiralova.cz",
    category: "Fotograf",
    token: "zbiralpnc",
    status: "live" as const,
    color: "#f5f0eb",
    accent: "#8b7355",
    screenshot: "/preview-zbiralova-demo.jpg",
    desc: "Svatební a rodinná fotografka Praha — WordPress TwentyTwentyOne + Visual Portfolio, 5 stránek: domů, svatby, rodiny, o mně, ceník. Portfolio galerie, voucher sekce.",
  },
  {
    slug: "honzakamenar-demo",
    name: "Demo Kameraman",
    origin: "honzakamenar.cz",
    category: "Videografie",
    token: "honza7r3y9",
    status: "live" as const,
    color: "#f5ede4",
    accent: "#8b6035",
    screenshot: "/preview-honzakamenar-demo.jpg",
    desc: "Svatební videograf Praha — Wix Thunderbolt, 5 stránek: domů, o mně, nabídka, reference, kontakt. Portfolio 6 svateb, hero foto, testimonials, process steps.",
  },
  {
    slug: "vasdj-demo",
    name: "Demo DJ",
    origin: "vasdj.cz",
    category: "DJ & Events",
    token: "vasdjakmzj",
    status: "live" as const,
    color: "#1a1a1a",
    accent: "#f15a24",
    screenshot: "/preview-vasdj-demo.jpg",
    desc: "DJ na svatbu, firemní akce, oslavy — SKY:CMS, 5 stránek: domů, služby, reference, tým, kontakt. Team foto, reference loga (BMW, IKEA, O2), oranžový design.",
  },
  {
    slug: "amdenevents-demo",
    name: "Demo Events",
    origin: "amdenevents.cz",
    category: "Event Agency",
    token: "amdend51f2",
    status: "live" as const,
    color: "#1a1a1a",
    accent: "#c9a84c",
    screenshot: "/preview-amdenevents-demo.jpg",
    desc: "Eventová agentura, teambuilding, konference — WordPress aevents theme, 5 stránek: domů, služby, reference, event agentura, kontakt. Owl carousel loga klientů, hero video sekce.",
  },
  {
    slug: "corleone-demo",
    name: "Demo Pizzeria",
    origin: "corleone.cz",
    category: "Restaurace & Pizzerie",
    token: "corleoneI472W5AS58",
    status: "live" as const,
    color: "#14100c",
    accent: "#d4b896",
    screenshot: "/preview-corleone-demo.jpg",
    desc: "Italská pizzeria & restaurace — Wix Thunderbolt, 5 stránek: domů, menu, nápoje, polední menu, kontakt. Tmavý elegantní design, foto interiéru, italská kuchyně.",
  },
];

export default function PreviewPage() {
  return (
    <div style={{ minHeight: "100vh", background: "#0a0a0a", color: "#fff", fontFamily: "system-ui, sans-serif" }}>
      {/* Header */}
      <div style={{ borderBottom: "1px solid #1e1e1e", padding: "20px 40px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <div>
          <span style={{ fontSize: 11, letterSpacing: 3, color: "#666", textTransform: "uppercase" }}>Venom SaaS</span>
          <h1 style={{ margin: "4px 0 0", fontSize: 22, fontWeight: 600, color: "#fff" }}>Výběr šablon</h1>
        </div>
        <span style={{ fontSize: 12, color: "#444", background: "#1a1a1a", padding: "4px 12px", borderRadius: 20 }}>Barbershop kategorie</span>
      </div>

      {/* Grid */}
      <div style={{ maxWidth: 1100, margin: "0 auto", padding: "48px 24px", display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))", gap: 28 }}>
        {TEMPLATES.map((t) => (
          <div key={t.slug} style={{
            background: "#111",
            border: `1px solid ${(t.status as string) === "wip" ? "#1e1e1e" : "#222"}`,
            borderRadius: 14,
            overflow: "hidden",
            opacity: (t.status as string) === "wip" ? 0.6 : 1,
            display: "flex",
            flexDirection: "column",
          }}>
            {/* Preview area */}
            <div style={{ position: "relative", height: 200, background: t.color, display: "flex", alignItems: "center", justifyContent: "center", overflow: "hidden" }}>
              {t.screenshot ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={t.screenshot} alt={t.name} style={{ width: "100%", height: "100%", objectFit: "cover", objectPosition: "top", display: "block" }} />
              ) : (
                <div style={{ textAlign: "center" }}>
                  <div style={{ fontSize: 36, marginBottom: 8 }}>🔨</div>
                  <div style={{ fontSize: 12, color: "#555" }}>Připravujeme</div>
                </div>
              )}
              {/* Status badge */}
              <div style={{
                position: "absolute", top: 12, right: 12,
                background: t.status === "live" ? "#16a34a" : "#374151",
                color: "#fff", fontSize: 10, fontWeight: 700,
                padding: "3px 10px", borderRadius: 20, letterSpacing: 1, textTransform: "uppercase",
              }}>
                {t.status === "live" ? "LIVE" : "WIP"}
              </div>
            </div>

            {/* Info */}
            <div style={{ padding: "20px 22px", flex: 1, display: "flex", flexDirection: "column", gap: 8 }}>
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                <h2 style={{ margin: 0, fontSize: 18, fontWeight: 700, color: "#fff" }}>{t.name}</h2>
                <span style={{ fontSize: 10, color: t.accent, background: "#1a1a1a", padding: "2px 8px", borderRadius: 10, border: `1px solid ${t.accent}30` }}>{t.category}</span>
              </div>
              <div style={{ fontSize: 11, color: "#555" }}>Zdroj: {t.origin}</div>
              <p style={{ margin: "4px 0 0", fontSize: 13, color: "#888", lineHeight: 1.6 }}>{t.desc}</p>
            </div>

            {/* Actions */}
            {t.status === "live" && t.token && (
              <div style={{ padding: "0 22px 20px", display: "flex", flexDirection: "column", gap: 8 }}>
                {/* Token */}
                <div style={{
                  background: "#0a0a0a", border: "1px solid #1e1e1e", borderRadius: 8,
                  padding: "10px 14px", display: "flex", alignItems: "center", justifyContent: "space-between",
                }}>
                  <div>
                    <div style={{ fontSize: 9, color: "#555", textTransform: "uppercase", letterSpacing: 1, marginBottom: 2 }}>Admin heslo</div>
                    <code style={{ fontSize: 13, color: t.accent, fontFamily: "monospace" }}>{t.token}</code>
                  </div>
                </div>

                {/* Buttons */}
                <div style={{ display: "flex", gap: 8 }}>
                  <a
                    href={`/demo/${t.slug}`}
                    target="_blank"
                    rel="noopener"
                    style={{
                      flex: 1, textAlign: "center", textDecoration: "none",
                      background: "#1e1e1e", color: "#ccc", fontSize: 12, fontWeight: 600,
                      padding: "10px 0", borderRadius: 8, border: "1px solid #2a2a2a",
                      transition: "background .2s",
                    }}
                  >
                    👁 Náhled
                  </a>
                  <a
                    href={`/demo/${t.slug}/login`}
                    target="_blank"
                    rel="noopener"
                    style={{
                      flex: 1, textAlign: "center", textDecoration: "none",
                      background: "#4f46e5", color: "#fff", fontSize: 12, fontWeight: 600,
                      padding: "10px 0", borderRadius: 8,
                      transition: "background .2s",
                    }}
                  >
                    ✏️ Editor
                  </a>
                </div>
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Footer note */}
      <div style={{ textAlign: "center", padding: "24px", color: "#333", fontSize: 12 }}>
        Venom SaaS — interní přehled šablon · <a href="/admin" style={{ color: "#555" }}>Platform Admin</a>
      </div>
    </div>
  );
}
